# Generated by Django 4.0.6 on 2022-08-04 05:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('fld_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fld_latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('fld_longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('fld_device_info', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_id', models.CharField(blank=True, db_column='fld_visit_id', max_length=50, null=True)),
                ('auto_check_out', models.BooleanField(db_column='fld_auto_check_out', default=False)),
                ('fld_is_active', models.BooleanField(default=True)),
                ('fld_is_delete', models.BooleanField(default=False)),
                ('fld_date', models.DateField(blank=True, null=True)),
                ('fld_time', models.TimeField(blank=True, null=True)),
                ('fld_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('fld_user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userDetail',
                'managed': True,
            },
        ),
    ]
