# Generated by Django 4.0.6 on 2022-07-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_userdetail_delete_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='id',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='Id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
